import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { adminDb } from "@/lib/firebase-admin";

const RAZORPAY_KEY_SECRET = process.env.RAZORPAY_KEY_SECRET || "";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const {
      razorpayOrderId,
      razorpayPaymentId,
      razorpaySignature,
      poolDetails,
      buyerId,
      buyerName,
    } = body;

    // Step 1: Validate required fields
    if (!razorpayOrderId || !razorpayPaymentId) {
      console.error("Verification failed: Missing required fields", { razorpayOrderId, razorpayPaymentId });
      return NextResponse.json(
        { success: false, error: "Missing payment details" },
        { status: 400 },
      );
    }

    // Step 2: Verify Razorpay signature if provided
    // The signature is generated by Razorpay after successful payment
    // We verify it to ensure the payment is authentic
    if (razorpaySignature && RAZORPAY_KEY_SECRET) {
      const generatedSignature = crypto
        .createHmac("sha256", RAZORPAY_KEY_SECRET)
        .update(`${razorpayOrderId}|${razorpayPaymentId}`)
        .digest("hex");

      if (generatedSignature !== razorpaySignature) {
        console.error("Payment signature verification failed", {
          expected: generatedSignature,
          received: razorpaySignature,
        });
        return NextResponse.json(
          { success: false, error: "Invalid signature" },
          { status: 400 },
        );
      }
      console.log("Signature verified successfully", { razorpayPaymentId });
    } else if (!razorpaySignature) {
      // No signature provided - still proceed with verification
      // This can happen if Razorpay doesn't return signature in some cases
      console.log("Proceeding without signature verification (immediate verification mode)", {
        razorpayOrderId,
        razorpayPaymentId,
      });
    }

    // Step 3: Process the payment and create/update records
    const now = new Date().toISOString();

    // If poolDetails provided, update the pool and create token payment record
    if (poolDetails?.poolId && buyerId) {
      const tokenPaymentId = `TP_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

      try {
        // Create token payment record in Firestore
        await adminDb.collection("tokenPayments").doc(tokenPaymentId).set({
          id: tokenPaymentId,
          orderId: tokenPaymentId,
          poolId: poolDetails.poolId,
          buyerId: buyerId,
          buyerName: buyerName || "Unknown Buyer",
          farmerId: poolDetails.farmerId,
          farmerName: poolDetails.farmerName || "Unknown Farmer",
          cropName: poolDetails.cropName || "Unknown",
          quantity: poolDetails.quantity || 0,
          pricePerQuintal: poolDetails.pricePerQuintal || 0,
          tokenAmount: poolDetails.tokenAmount || 0,
          totalAmount: poolDetails.totalAmount || 0,
          razorpayOrderId: razorpayOrderId,
          razorpayPaymentId: razorpayPaymentId,
          razorpaySignature: razorpaySignature || null,
          paymentMode: "razorpay",
          status: "verified",
          farmerConfirmed: false,
          farmerDenied: false,
          paidAt: now,
          verifiedAt: now,
          createdAt: now,
          updatedAt: now,
          paymentVerified: true,
          verificationId: `VFY_${Date.now()}`,
        });

        // Update the pool with buyer info and mark as token-paid
        await adminDb.collection("pools").doc(poolDetails.poolId).update({
          buyerId: buyerId,
          buyerName: buyerName || "Unknown Buyer",
          tokenAmount: poolDetails.tokenAmount || 0,
          status: "token-paid",
          razorpayPaymentId: razorpayPaymentId,
          razorpayOrderId: razorpayOrderId,
          tokenPaidAt: now,
          updatedAt: now,
        });

        // Send notification to farmer
        await adminDb.collection("notifications").add({
          userId: poolDetails.farmerId,
          type: "payment",
          title: "Token Payment Received",
          message: `Buyer ${buyerName || "A buyer"} has paid ₹${poolDetails.tokenAmount || 0} token for ${poolDetails.quantity || 0} quintals of ${poolDetails.cropName || "crop"} via Razorpay. Check your orders.`,
          relatedId: tokenPaymentId,
          read: false,
          createdAt: now,
        });

        console.log("Payment verified and token payment created", {
          tokenPaymentId,
          poolId: poolDetails.poolId,
          razorpayPaymentId,
        });

        return NextResponse.json({
          success: true,
          orderId: tokenPaymentId,
          razorpayPaymentId: razorpayPaymentId,
          message: "Payment verified and token payment created",
        });
      } catch (dbError) {
        console.error("Database error during payment verification:", dbError);
        return NextResponse.json(
          { success: false, error: "Failed to record payment" },
          { status: 500 },
        );
      }
    }

    // If no poolDetails, just verify the signature (for webhook compatibility)
    console.log("Payment signature verified (no pool details)", {
      razorpayOrderId,
      razorpayPaymentId,
    });

    return NextResponse.json({
      success: true,
      message: "Payment signature verified",
      razorpayPaymentId: razorpayPaymentId,
    });
  } catch (error) {
    console.error("Payment verification error:", error);
    return NextResponse.json(
      { success: false, error: "Verification failed" },
      { status: 500 },
    );
  }
}